I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/naoko/sex_scene_1.rpy", line 103, in script
    show naoko_sex1-8_outside-1 with cum_flash
TypeError: Fade() got multiple values for keyword argument 'old_widget'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/naoko/sex_scene_1.rpy", line 103, in script
    show naoko_sex1-8_outside-1 with cum_flash
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 1356, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\exports.py", line 1481, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 2227, in do_with
    clear=clear)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 2672, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 3012, in interact_core
    new_widget=layers_root)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\curry.py", line 40, in __call__
    **dict(self.kwargs.items() + kwargs.items()))
TypeError: Fade() got multiple values for keyword argument 'old_widget'

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Break: The Rematch v0.6.0-alpha
Fri Dec 28 15:12:13 2018
